### ISSUE TITLE
Bug - SIP PROFILE

### ISSUE THREAD

**Issue by rgazetta** [iNextrix/ASTPP#457] opened 2018-07-31 13:10 UTC
BUG

Every time I create a new account or the client edits the SIP devices, the SIP PROFILE is left blank, it is only corrected if ADMIN edit and correct it.

**Comment by devangn** [comment] 2018-08-03 05:41
@rgazetta
Please share the exact steps to reproduce this because I tried editing/creating the sip device from customer account but default sip-profile is assigned to them correctly.

**Comment by rgazetta** [comment] 2018-08-03 11:34
The client accesses the panel and edits the sip device.
As soon as it saves everything still works, however in the admin panel I can see that the sip profile field is blank.

Via admin, if edit and save again the sip profile returns to normal.

I edited the default language in the constants.php file, could this cause this failure?

/ *
  | | ------------------------------------------------ --------------------------
  * | Defines default language for UI
  | | ------------------------------------------------ --------------------------
  * |
  * | Set en_EN for English language
  * | Set is_EN for Spanish language
  * | Set fr_FR for French language
  * | Set pt_BR for Portuguese
  * |
  * /
define ('DEFAULT_LANGUAGE', 'pt_BR');

/ * End of file constants.php * /
/ * Location: ./application/config/constants.php * /

**Comment by devangn** [comment] 2018-11-23 07:17
@rgazetta We have checked creating sip device under customer account and then checked the same device's configuration from admin account, the sip profile seem to assign correctly.
We are checking with v3.6.
If you find our regeneration step not same as yours or if you want to share screen shot, please share them.

**Comment by rgazetta** [comment] 2018-11-23 10:49
@devangn
The client accesses the panel and edits the sip device.
As soon as it saves everything still works, however in the admin panel I can see that the sip profile field is blank.

Via admin, if edit and save again the sip profile returns to normal.

**Comment by devangn** [comment] 2018-12-24 04:58
@rgazetta We have tried creating new account and checked the sip devices configs, they seem fine.
We have created new sip device from admin portal and tried editing from client portal; and checked configs in admin portal, they seem fine.
We have created new sip device from client portal and tried editing from client portal and checked them from admin portal, they seem fine.

Can you please elaborate exact steps to regenerate the issue you are facing?

**Comment by devangn** [comment] 2019-03-12 17:53
Closing issue because of no activity since days.

**Closed by devangn** 2019-03-12 17:53 UTC
