### ISSUE TITLE
ASTPP 3.5, invoice description is blank

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#228] opened 2017-09-12 16:42 UTC
With last ASTPP when I refill an account, the description in the invoice is empty.

See the attachment
[INV_00005-3.pdf](https://github.com/iNextrix/ASTPP/files/1296702/INV_00005-3.pdf)

**Comment by smrdoshi** [comment] 2017-09-15 04:59
Did you enter description while doing refill of account?
Can you see description in charges history report?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by smrdoshi** [comment] 2017-10-04 11:14
Waiting for the feedback.

**Comment by drenda** [comment] 2017-10-04 19:39
I didn't insert description, but into an invoice, even if the description is empty at least I would expect to see what is the charge for.

THanks

**Comment by smrdoshi** [comment] 2017-10-05 12:48
Hi @drenda 

I can see the entry in your previous pdf with 4 ERU. Is there anything else you are expecting in invoice / receipt pdf?

**Comment by drenda** [comment] 2017-10-05 12:51
Yes, here in italy an invoice without a description for the item is not valid. I see your point to fill the description field and ok. But even if the description is empty I guess should appears something like "Voip Refill" or something like that.

**Comment by smrdoshi** [comment] 2017-10-05 12:54
Alright. At the moment that code is not available. So it will display whatever information you will enter into description while doing refill. 

Closing the issue as this is not a bug.

**Closed by smrdoshi** 2017-10-05 12:54 UTC
Labels: discussion
