### ISSUE TITLE
JQuery version error

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#460] opened 2018-08-08 18:34 UTC
Browsing to any page in the GUI results in the following jQuery errors when viewing Chrome or FireFox element inspection console view.

```
(index):101 Uncaught ReferenceError: SyntaxHighlighter is not defined
    at (index):101
(anonymous) @ (index):101
maxcdn_bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher
    at maxcdn_bootstrap.min.js:6
    at maxcdn_bootstrap.min.js:6
```

**Comment by AlexHeylin** [comment] 2018-08-16 15:14
I also see this issue.

**Comment by AlexHeylin** [comment] 2018-09-05 08:42
This appears to be a duplicate of #170 
https://github.com/iNextrix/ASTPP/issues/170

**Comment by smrdoshi** [comment] 2018-09-05 12:33
That's right. Its duplicate of #170 

Closing this bug.

**Closed by smrdoshi** 2018-09-05 12:33 UTC
