### ISSUE TITLE
Delete all termination rates on selected trunk

### ISSUE THREAD

**Issue by juancarlosg6** [iNextrix/ASTPP#81] opened 2016-08-26 01:19 UTC
We do a search on "Termination Rates" and select a specific "trunk" on search, this show only the rates for this trunk, we select "Delete Search Record", show the correct quantity of register, but whe i select, delete all rates about all trunks not only the selected trunk.

![image](https://cloud.githubusercontent.com/assets/5462130/17990994/6c0ad0ce-6b00-11e6-9b35-4c1d5665d27d.png)

**Comment by dev-astpp** [comment] 2016-08-26 07:18
1. If you want to delete specific trunk's rates then first search using trunk and click on delete search record button 
2. If you want to delete all records then just click on search button it show you "Delete Search Record" button click on that it will delete all records

**Comment by juancarlosg6** [comment] 2016-08-27 15:26
Yes,i only search for specific trunk first  i can see only the rates of the trunk selected, later i do click on delete search record and , but the system delete all record of all trunks.

**Comment by dev-astpp** [comment] 2016-09-08 05:34
Are you using windows system?

**Comment by dev-astpp** [comment] 2016-11-04 09:04
Didn't get further information to reproduce this issue, So we are closing this issue

**Closed by dev-astpp** 2016-11-04 09:04 UTC
Labels: discussion

**Comment by Analogia** [comment] 2017-10-25 19:21
This is still happens in 3.5 
you click on termination rate
then search then chose a trunk then delete search records and wailllla all your termination rates got deleted.  i can reproduce it every time. 
using chrome and windows 10. 
installed with install script on vanilla Jessie.

**Comment by smrdoshi** [comment] 2017-11-01 11:04
We are unable to reproduce the issue. Can you provide chrome version which you are using?
