### ISSUE TITLE
Invoice Downlod link not working

### ISSUE THREAD

**Issue by farah12** [iNextrix/ASTPP#154] opened 2016-11-12 15:15 UTC
I installed ASTPP 3.0 few days ago. When I try to download invoice from any customer portal, it doesn't work. It shows an erro
![doc1](https://cloud.githubusercontent.com/assets/23419046/20238792/e0848be8-a8ea-11e6-8d07-9de22cee613a.png)
r. I have attached the error page.

**Comment by dev-astpp** [comment] 2016-11-18 04:19
Hello Farah,

As per your screenshot and reported bug we try to reproduce that issue but unfortunately we can't get that error.

Will you please let us know the exalt step of reproduce?

Like :-
1. Your user type prepaid/postpaid
2. What action you perform after create customer (recharge, subscription etc)
3. Or you are trying after delete some specific data and after that downloading invoice?

**Comment by smrdoshi** [comment] 2016-12-02 14:07
Any update @farah12? If you are still facing the problem then please provide us steps to reproduce the issue.

**Comment by dev-astpp** [comment] 2016-12-16 04:49
There is no any update since long for reproduce step. So we are closing this issue as invalid

**Closed by dev-astpp** 2016-12-16 04:49 UTC
Labels: invalid
