### ISSUE TITLE
Subscriptions --> Amount 

### ISSUE THREAD

**Issue by volga629** [iNextrix/ASTPP#216] opened 2017-08-15 00:27 UTC
Hello Everyone,
Under Subscriptions --> Amount  impossible to save or specify amount in local currency.
It always stays 0.  I tried on demo server and our installation and result the same.

![subscriptions-amount](https://user-images.githubusercontent.com/3235221/29297424-429c8af4-8137-11e7-815b-caca789841e4.png)

**Comment by smrdoshi** [comment] 2017-08-17 09:13
What is the local currency?

I just entered 0.10 in test subscription and its showing correctly in UI.
http://latest.astppbilling.org/charges/periodiccharges/

Please provide more information reproduce the issue.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by volga629** [comment] 2017-08-17 11:32
Hello,
Yes this local currency. 

Is this URL http://latest.astppbilling.org/charges/periodiccharges/ last git pull ? Because our version is was installed through official wiki.

The screenshot is ASTPP demo server you can try reproduce issue from there are.

demo.astppbilling.org/

**Comment by volga629** [comment] 2017-08-17 13:22
After some investigation we found that two issues are present.

1. Our version is behind of latest git which this bug already has being fixed there are.
2. Numbers hitting limits. (Please see screenshot). Need to allow up to the millions


![image_from_skype](https://user-images.githubusercontent.com/3235221/29414321-b0cc951e-8335-11e7-96f2-9d3e250416d0.png)

**Comment by smrdoshi** [comment] 2017-09-05 12:33
That is fixed in version v3.5. Upgrade to latest version and test it out.

**Closed** 2017-09-05 12:33 UTC
Labels: bug confirmed

**Comment by volga629** [comment] 2017-09-05 21:49
Thank you for quick fix. We will test it soon.
