### ISSUE TITLE
Wrong balance display in Android ASTPP Dialer 2.0.1 with ASTPP 3.0

### ISSUE THREAD

**Issue by watoan** [iNextrix/ASTPP#23] opened 2016-08-05 04:00 UTC
1. Logged in with (Android) ASTPP Dialer 2.0.1 with ASTPP 3.0 but the account balance showing USD 0.00, tried to update the port 8089 in APP setting "Balance API URL" but no effect

2. Suggestion: Dialer Balance currency display follows the "Currency" in ASTPP customer settings

**Comment by smrdoshi** [comment] 2016-08-06 04:32
I just confirmed on demo and it seems to be working fine. 
Can you please confirm if your customer currency set correctly?

Here is the test result on demo : 
http://latest.astppbilling.org/getbalance/4810338297
Result : Balance : 1418.67 INR

Please confirm.

**Comment by watoan** [comment] 2016-08-06 13:56
Yes, the link in your demo is showing the information correctly.

But on my own site, I tried the same and put "http://1.2.3.4:8089/getbalance/5294732849" (where 5294732849 is a SIP device username I have newly created), and it is linked to the default customer "2457848300" which has US$1.00, but it shows the message "Please enter proper username of SIP Account".

Could you please advise anything else I could check and try?

**Comment by smrdoshi** [comment] 2016-08-09 11:27
This issue has been fixed now.

**Closed by smrdoshi** 2016-08-09 11:27 UTC
Labels: confirmed, discussion, new bug
